const quizWereWolf = [    
    {
        id: 1,
        quest: 'Como surgiu os lobimens?',
        q1: 'Aliens os trouxeram para a terra',
        q2: 'Foram achados em um navio pirata',
        q3: 'Foram criados por uma maldição',
        q4: 'Foram desenvolvidos em laboratorios',
        q5: 'Surgiram por causa de um feitiço',
        qR: 'Foram criados por uma maldição',
        
    },
    {
        id: 2,
        quest: 'Oque são lobisomens?',
        q1: 'Humanos que viram uma criatura durante a lua cheia',
        q2: 'Fantasmas do Scooby Doo',
        q3: 'Lobos do Ártico',
        q4: 'Personagens da Turma da Mônica',
        q5: 'Histórias de acampamento',
        qR: 'Humanos que viram uma criatura durante a lua cheia',
    },
    {
        id: 3,
        quest: 'Como os lobisomens ficaram famosos?',
        q1: 'Por causa de suas lendas',
        q2: 'Por causa dos desenhos',
        q3: 'Por causa dos Três porquinhos',
        q4: 'Por causa da chapéuzinho vermelho',
        q5: 'Por causa do Governo',
        qR: 'Por causa de suas lendas',
    },
    {
        id: 4,
        quest: 'De onde veio a lenda dos Lobisomens?',
        q1: 'Da Escócia',
        q2: 'Do Canadá',
        q3: 'Da Grécia',
        q4: 'De Portugal',
        q5: 'Da Indonésia',
        qR: 'Da Grécia',
    },
    {
        id: 5,
        quest: 'Como se detém um Lobisomen?',
        q1: 'Com bala de prata no coração',
        q2: 'Com uma boa conversa',
        q3: 'Não tem como',
        q4: 'Destruindo a lua',
        q5: 'Com um Fuzil',
        qR: 'Com bala de prata no coração',
    },
]
const quizSamurai = [
    {
        id: 1,
        quest: 'Oque são Samurai?',
        q1: 'Jogadores de futebol',
        q2: 'Guerreiros japoneses',
        q3: 'Dinossauros que viviam no Brasil',
        q4: 'Cientistas Americanos',
        q5: 'Peixes que vivem no Oceano',
        qR: 'Guerreiros japoneses',
        
    },
    {
        id: 2,
        quest: 'Oque faziam os Samurai?',
        q1: 'Jogavam bola',
        q2: 'Apresentavam um programa de TV',
        q3: 'Particapavam das Olimpíadas',
        q4: 'Serviam como soldados',
        q5: 'Cantavam em shows',
        qR: 'Serviam como soldados',
    },
    {
        id: 3,
        quest: 'Qual arma de ficou famosa por causa deles',
        q1: 'Fuzil',
        q2: 'Revolver',
        q3: 'Karambit',
        q4: 'Katana',
        q5: 'Nunchako',
        qR: 'Katana',
    },
    {
        id: 4,
        quest: 'De que país se originou os Samurai',
        q1: 'Japão',
        q2: 'França',
        q3: 'Estados Unidos',
        q4: 'México',
        q5: 'Turquia',
        qR: 'Japão',
    },
    {
        id: 5,
        quest: 'Oque eram os Ronin',
        q1: 'Um samurai que não possui mestre',
        q2: 'Lutadores profissionais',
        q3: 'Lagos da família real',
        q4: 'Jogos de computador',
        q5: 'Um desenhista renomado',
        qR: 'Um samurai que não possui mestre',
    },
]

export {quizWereWolf, quizSamurai}